using './main.bicep'

param location = 'westus2'
param functionName = 'caldova-genie-obo-fn'
param planName = 'caldova-showcase-plan'
param storageNamePrefix = 'genieobo'
param vnetName = 'caldova-dbx-vnet-westus2'
param apimVnetName = 'caldova-apim-westus-vnet'
param apimName = 'caldova-apim-westus'
param insightsName = 'caldova-genie-obo-insights'
param tenantId = '12a4b86b-e64c-43f9-af05-d9130a72dfd2'
param apiClientId = 'bdd127ff-fd4c-45f5-b553-ff77a7755161'
param connectorClientId = '8127fb92-0641-4f6e-9d6e-f508e18e9606'
param workspaceUrl = 'https://adb-7405616934814750.10.azuredatabricks.net'
param oboScope = 'Genie.Access'
param jwkFetchTimeoutMs = 5000
param tokenExchangeTimeoutMs = 10000
param integrationSubnetName = 'genie-obo-integration'
param privateEndpointSubnetName = 'private-endpoints'
param deploymentContainerName = 'deployments'
param storageSkuName = 'Standard_LRS'
param blobDeleteRetentionDays = 7
param functionsExtensionVersion = '~4'
param nodeVersion = '~22'
param netFrameworkVersion = 'v8.0'
