// Generated by scripts/generate-foundry-videos.mjs. Do not edit directly.
export const FOUNDRY_VIDEOS = [
  {
    "sequence": "01",
    "title": "Teams agent with Foundry, APIM, and Databricks",
    "description": "See the end-to-end Teams agent call Microsoft Foundry, traverse API Management, and query Databricks Genie with user-delegated authorization.",
    "duration": "11:38",
    "file": "assets/foundry/videos/Teams%20Agent%20-%20Bot%20-%20Foundry%20-%20APIM%20-%20Databricks%20Demo.mp4"
  }
] as const;
