using './main.bicep'

param location = 'westus'
param foundryAccountName = 'foundry-myaacoub-private'
param foundrySkuName = 'S0'
param publicNetworkAccess = 'Enabled'
param projectName = 'sales-poc'
param projectDisplayName = 'sales-poc'
param projectDescription = 'Private Foundry project for the Databricks MCP agent'
param projectCapabilityHostName = 'caphostproj'
param modelDeploymentName = 'gpt-6-astra'
param modelName = 'gpt-6-astra'
param modelVersion = '2026-09-03'
param modelSkuName = 'GlobalStandard'
param modelCapacity = 500
param modelVersionUpgradeOption = 'OnceNewDefaultVersionAvailable'
param vnetName = 'caldova-apim-westus-vnet'
param clientVnetName = 'caldova-dbx-vnet-westus2'
param privateEndpointSubnetName = 'private-endpoints'
param agentSubnetName = 'foundry-agent'
param agentSubnetPrefix = '10.191.2.0/24'
param tags = {
	project: 'caldova-databricks-apim-private'
	environment: 'caldova'
	managed_by: 'bicep'
	component: 'foundry-private'
}
